// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeRNC2lrdKMN3e51fRh_zsEZO20kQ_RuY',
    appId: '1:40488551836:web:aca24262a23f832f5d7459',
    messagingSenderId: '40488551836',
    projectId: 'addislancersapp',
    authDomain: 'addislancersapp.firebaseapp.com',
    storageBucket: 'addislancersapp.appspot.com',
    measurementId: 'G-V3XEW9VW4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoCWVC23FR2T9fsc72aaCcqaP-myIIWEs',
    appId: '1:40488551836:android:05cd6be8289151315d7459',
    messagingSenderId: '40488551836',
    projectId: 'addislancersapp',
    storageBucket: 'addislancersapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTfxUZuLVWhqx4qX0o8vwcEw7x9IaST0g',
    appId: '1:40488551836:ios:7cc6106ae0d304195d7459',
    messagingSenderId: '40488551836',
    projectId: 'addislancersapp',
    storageBucket: 'addislancersapp.appspot.com',
    iosClientId: '40488551836-ekscecbthel3n0et7po1hsoa0kkpij8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.addislancersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTfxUZuLVWhqx4qX0o8vwcEw7x9IaST0g',
    appId: '1:40488551836:ios:7cc6106ae0d304195d7459',
    messagingSenderId: '40488551836',
    projectId: 'addislancersapp',
    storageBucket: 'addislancersapp.appspot.com',
    iosClientId: '40488551836-ekscecbthel3n0et7po1hsoa0kkpij8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.addislancersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeRNC2lrdKMN3e51fRh_zsEZO20kQ_RuY',
    appId: '1:40488551836:web:980c07ce370b214e5d7459',
    messagingSenderId: '40488551836',
    projectId: 'addislancersapp',
    authDomain: 'addislancersapp.firebaseapp.com',
    storageBucket: 'addislancersapp.appspot.com',
    measurementId: 'G-6G9Q8421GW',
  );

}