// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIPbTuTmpC_SPZY7bi5J7YHB8SeFmga90',
    appId: '1:862480491701:web:c1945616ae0c2ee6268afc',
    messagingSenderId: '862480491701',
    projectId: 'addislancersapp-5a6ee',
    authDomain: 'addislancersapp-5a6ee.firebaseapp.com',
    storageBucket: 'addislancersapp-5a6ee.appspot.com',
    measurementId: 'G-8X24RXHNQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7qcdNf8KaxS9_X0bJsh55unX2eSaSTrA',
    appId: '1:862480491701:android:57ec2bec95d26c50268afc',
    messagingSenderId: '862480491701',
    projectId: 'addislancersapp-5a6ee',
    storageBucket: 'addislancersapp-5a6ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHVP26hjBXY8HU8LYHG92idhnBurM3Z-8',
    appId: '1:862480491701:ios:2b848baec916e474268afc',
    messagingSenderId: '862480491701',
    projectId: 'addislancersapp-5a6ee',
    storageBucket: 'addislancersapp-5a6ee.appspot.com',
    iosBundleId: 'com.example.addislancersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHVP26hjBXY8HU8LYHG92idhnBurM3Z-8',
    appId: '1:862480491701:ios:2b848baec916e474268afc',
    messagingSenderId: '862480491701',
    projectId: 'addislancersapp-5a6ee',
    storageBucket: 'addislancersapp-5a6ee.appspot.com',
    iosBundleId: 'com.example.addislancersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIPbTuTmpC_SPZY7bi5J7YHB8SeFmga90',
    appId: '1:862480491701:web:08a3d5f974f3259c268afc',
    messagingSenderId: '862480491701',
    projectId: 'addislancersapp-5a6ee',
    authDomain: 'addislancersapp-5a6ee.firebaseapp.com',
    storageBucket: 'addislancersapp-5a6ee.appspot.com',
    measurementId: 'G-Y1MRZKCXKG',
  );
}
